C
C**********************************************************************C
C**********************************************************************C
C**********************************************************************C
C
      REAL FUNCTION CSEDTAUS(DENBULK,IOPT)
C
C **  CALCULATES CRITIAL STRESS FOR SURFACE EROSION OF COHESIVE 
C **  SEDIMENT AS A FUNCTION OF BED BULK DENSITY
C
C **  IOPT=1  BASED ON 
C **
C **  HWANG, K. N., AND A. J. MEHTA, 1989: FINE SEDIMENT DRODIBILITY
C **  IN LAKE OKEECHOBEE FLORIDA. COASTAL AND OCEANOGRAPHIC ENGINEERING
C **  DEPARTMENT, UNIVERSITY OF FLORIDA, GAINESVILLE, FL32661
C
C **  IOPT=2  BASED ON 
C **
C **  HWANG, K. N., AND A. J. MEHTA, 1989: FINE SEDIMENT DRODIBILITY
C **  IN LAKE OKEECHOBEE FLORIDA. COASTAL AND OCEANOGRAPHIC ENGINEERING
C **  DEPARTMENT, UNIVERSITY OF FLORIDA, GAINESVILLE, FL32661
C
      IF(IOPT.EQ.1) THEN
       DENBULK=0.001*DENBULK
       IF(DENBULK.LE.1.065) THEN
         CSEDTAUS=0.0
        ELSE
         TMP=(DENBULK-1.065)**0.2
         CSEDTAUS=0.001*(0.883*TMP+0.05)
       END IF
      END IF
C
      IF(IOPT.EQ.1) THEN
       DENBULK=0.001*DENBULK
       IF(DENBULK.LE.1.065) THEN
         CSEDTAUS=0.0
        ELSE
         TMP=(DENBULK-1.065)**0.2
         CSEDTAUS=0.001*(0.883*TMP+0.05)
       END IF
      END IF
C
      RETURN
      END
